---
# tasks file for lighthouse-role
- name: Install EPEL Repo
  yum:
    name=epel-release
    state=present

- name: Install nginx
  yum:
    name=nginx
  notify:
    - nginx systemd

- name: Install git
  yum:
    name=git

- name: write config with jinja2
  ansible.builtin.template:
     src: nginx.conf.j2
     mode: 0644
     dest: /etc/nginx/nginx.conf
     owner: nginx
     group: nginx
  notify:
    - nginx systemd
- name: Clone repo
  ansible.builtin.git:
     repo: https://github.com/VKCOM/lighthouse.git
     dest: /usr/share/nginx/index
