---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
  - name: aragast
    image: aragast/netology:latest
    pre_build_image: true
  - name: centos
    image: centos:7
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
